#pragma once

constexpr int PRECISION = 200;
constexpr int INDEXMAP_PRECISION = PRECISION >> 2;
constexpr int INDEXMAP_FACE_STRIDE = INDEXMAP_PRECISION * INDEXMAP_PRECISION;
constexpr int INDEXMAP_CORNER_STRIDE = INDEXMAP_FACE_STRIDE * 3;
constexpr int INDEXMAP_DATALENGTH = INDEXMAP_CORNER_STRIDE * 8;
constexpr int VERTICES_DATALENGTH = (PRECISION + 1) * (PRECISION + 1) * 4;
constexpr int STRIDE = (PRECISION + 1) * 2;
constexpr int LANDPERCENT_NUM = STRIDE / 2;
constexpr int LAND_DATALENGTH = 40401;
constexpr float MATHF_PI = 3.1415927f;

constexpr int PERM_LENGTH = 512;

constexpr float GAS_PLANET_REAL_RADIUS = 800.0f;
constexpr float NORMAL_PLANET_RADIUS = 200.0f;
constexpr float NORMAL_PLANET_REAL_RADIUS = NORMAL_PLANET_RADIUS * 1.0f;
