class PlanetData:
    name: str
    type: str
    type_id: int
    singularity: int
    singularity_str: list[str]
    seed: int
    lumino: float
    wind: float
    radius: float #AU
    liquid: int
    is_gas: bool
    dsp_level: int
    veins_group: list[int]
    veins_point: list[int]
    gas_veins: list[float]

class StarData:
    name: str
    type: str
    type_id: int
    seed: int
    dyson_lumino: float
    dyson_radius: float #m
    distance: float #LY
    pos: list[float]
    planets: list[PlanetData]
    veins_group: list[int]
    veins_point: list[int]
    gas_veins: list[float]
    liquid: list[int]

class GalaxyData:
    seed: int
    star_num: int
    stars: list[StarData]
    veins_group: list[int]
    veins_point: list[int]
    gas_veins: list[float]
    liquid: list[int]

class MoonCondition:
    satisfy_num: int = 1
    dsp_level: int = 0
    type: int = 0
    liquid: int = 0
    singularity: int = 0
    need_veins: int = 0
    veins_group: list[int] = [0] * 14
    veins_point: list[int] = [0] * 14

class PlanetCondition:
    satisfy_num: int = 1
    dsp_level: int = 0
    type: int = 0
    liquid: int = 0
    singularity: int = 0
    need_veins: int = 0
    veins_group: list[int] = [0] * 14
    veins_point: list[int] = [0] * 14
    moons: list[MoonCondition] = []

class StarCondition:
    satisfy_num: int = 1
    type: int = 0
    distance: float = 1000.0
    dyson_lumino: float = 0.0
    need_veins: int = 0
    veins_group: list[int] = [0] * 14
    veins_point: list[int] = [0] * 14
    planets: list[PlanetCondition] = []

class GalaxyCondition:
    need_veins: int = 0
    veins_group: list[int] = [0] * 14
    veins_point: list[int] = [0] * 14
    stars: list[StarCondition] = []
    planets: list[PlanetCondition] = []

class Seed:
    seed_id: int
    star_num: int

class SeedManager:
    def __init__(self): ...
    def add_seed(self, seed: int, star_num: int) -> None: ...
    def del_seed(self, seed: int, star_num: int) -> None: ...
    def clear(self) -> None: ...
    def reset_index(self) -> None: ...
    def get_seeds_count(self) -> int: ...
    def get_seeds(self, batch_size: int) -> list[Seed]: ...

class GetDataManager:
    def __init__(self, max_thread:int, quick:bool, max_cache:int): ...
    def add_task(self, seed_id:int, star_num:int) -> None: ...
    def shutdown(self) -> None: ...
    def get_results(self) -> list[GalaxyData]: ...

class CheckPreciseManager:
    def __init__(self, seed_manager:SeedManager, galaxy_condition:dict, quick:bool, max_thread:int): ...
    def run(self) -> None: ...
    def is_running(self) -> bool: ...
    def shutdown(self) -> None: ...
    def get_task_num(self) -> int: ...
    def get_task_progress(self) -> int: ...
    def get_result_num(self) -> int: ...
    def get_last_result(self) -> Seed: ...
    def get_results(self) -> list[Seed]: ...

class CheckBatchManager:
    def __init__(self, start_seed:int, end_seed:int, start_star_num:int, end_star_num:int, galaxy_condition:dict, quick:bool, max_thread:int): ...
    def run(self) -> None: ...
    def is_running(self) -> bool: ...
    def shutdown(self) -> None: ...
    def get_task_num(self) -> int: ...
    def get_task_progress(self) -> int: ...
    def get_result_num(self) -> int: ...
    def get_last_result(self) -> Seed: ...
    def get_results(self) -> list[Seed]: ...

def do_init_c() -> None: ...
def set_device_id_c(device_id:int) -> bool: ...
def get_device_id_c() -> int: ...
def set_local_size_c(local_size:int) -> None: ...
def get_local_size_c() -> int: ...
def get_device_info_c() -> list[str]: ...
def get_support_double_c() -> bool: ...
def galaxy_condition_to_struct(galaxy_condition:dict) -> GalaxyCondition: ...
def get_galaxy_data_c(seed:int, star_num:int, quick:bool) -> GalaxyData: ...
def check_batch_c(start_seed:int, end_seed:int, start_star_num:int, end_star_num:int, galaxy_condition:dict, quick: bool) -> list[str]: ...
def check_precise_c(seed_list:list[int], star_num_list:list[int], galaxy_condition: dict, quick: bool) -> list[str]: ...
