def get_galaxy_data(seed:int, star_num:int) -> dict: ...

def check_seed(seed:int, star_num:int, galaxy_condition:dict) -> bool: ...

def check_batch(start_seed:int, end_seed:int, star_num:int, galaxy_condition:dict) -> list: ...