def get_galaxy_data_c(seed:int, star_num:int) -> str: ...
def check_batch_c(start_seed:int, end_seed:int, start_star_num:int, end_star_num:int, galaxy_condition:str, galaxy_condition_simple:str) -> list: ...
