name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        required: true
        type: string
  push:
    tags:
      - V*.*
      - v*.*

permissions:
  contents: write

jobs:
  build:
    uses: ./.github/workflows/build.yml
    with:
      version: ${{ github.event.inputs.version || github.ref_name }}

  release:
    runs-on: windows-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@main
        with:
          fetch-depth: 0

      - name: Download Artifact
        uses: actions/download-artifact@v6
        with:
          path: release/
          merge-multiple: true

      - name: Create ZIP archive
        run: |
          Compress-Archive -Path release/* -DestinationPath dsp_search_seed_${{ github.event.inputs.version || github.ref_name }}.zip
        shell: pwsh

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          name: ${{ github.event.inputs.version || github.ref_name }}
          tag_name: ${{ github.event.inputs.version || github.ref_name }}
          files: |
            dsp_search_seed_${{ github.event.inputs.version || github.ref_name }}.zip
          body_path: release_notes.md
          target_commitish: ${{ github.sha }}
          token: ${{ secrets.GITHUB_TOKEN }}
          fail_on_unmatched_files: false