name: Release

on:
  workflow_dispatch:
  push:
    tags:
      - V*.*
      - v*.*

jobs:
  build:
    uses: ./.github/workflows/build.yml

  release:
    runs-on: windows-latest
    needs: build
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v6
        with:
          path: release/
          merge-multiple: true

      - name: 调试文件结构
        run: |
          echo "工作目录: $PWD"
          echo "release目录内容:"
          ls -la
          ls -la release/ || echo "release目录不存在"
          find . -name "*" -type f | head -20

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          name: ${{ github.ref_name }}
          tag_name: ${{ github.ref_name }}
          files: |
            release/*
          target_commitish: ${{ github.sha }}
          token: ${{ secrets.GITHUB_TOKEN }}
          fail_on_unmatched_files: false